development:
  adapter: postgresql
  encoding: unicode
  database: alpha_blog_development
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: alpha_blog_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: alpha_blog_production
  username: postgres
  password: postgres
